#!/bin/bash
. /usr/local/lib/reverse_proxy/add_server_to_reverse_proxy.sh

echo "Container ip:"
read -r CONTAINER_IP
echo "Container name:"
read -r CONTAINER_NAME
echo "Server name:"
read -r SERVER_NAME
echo "URI:"
read -r URI
echo "Service port:"
read -r SERVICE_PORT
echo "Protocol:"
read -r PROTOCOL
echo "Proxy network:"
read -r PROXY_NETWORK
echo "Container network:"
read -r CONTAINER_NETWORK

add_server_to_reverse_proxy "$CONTAINER_NAME" "$SERVER_NAME" "$URI" "$CONTAINER_IP" "$PROTOCOL" "$PROXY_NETWORK" "$CONTAINER_NETWORK" "$SERVICE_PORT"