#!/bin/bash
. /usr/local/lib/docker_utils/docker_run_with_volume.sh
. /usr/local/lib/iptables_utils/allow_forward_to_server_from_any.sh

echo "Container name:"
read -r CONTAINER_NAME
echo "Service port:"
read -r SERVICE_PORT
echo "Image name:"
read -r IMAGE_NAME
echo "Internal network name:"
read -r INTERNAL_NETWORK
echo "Public port:"
read -r PUBLIC_PORT
echo "Protocol:"
read -r PROTOCOL
echo "Public interface:"
read -r PUBLIC_INTERFACE

CONTAINER_IP=$(docker_run_with_volume "$CONTAINER_NAME" "$SERVICE_PORT" "$INTERNAL_NETWORK" "$IMAGE_NAME" "$CONTAINER_NAME-sites" "/etc/nginx/sites-available")

allow_forward_to_server_from_any "$PROTOCOL" "$PUBLIC_INTERFACE" "$INTERNAL_NETWORK" "$PUBLIC_PORT" "$CONTAINER_IP" "$SERVICE_PORT"
